# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloudx_connector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cloudx_connector.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63loudx_connector.proto\"\"\n\x0fPlatformRequest\x12\x0f\n\x07\x63lintId\x18\x01 \x01(\t\";\n\x11\x43omponentResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2M\n\x0f\x43loudxConnector\x12:\n\x0eShowComponents\x12\x10.PlatformRequest\x1a\x12.ComponentResponse\"\x00\x30\x01\x62\x06proto3'
)




_PLATFORMREQUEST = _descriptor.Descriptor(
  name='PlatformRequest',
  full_name='PlatformRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clintId', full_name='PlatformRequest.clintId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_COMPONENTRESPONSE = _descriptor.Descriptor(
  name='ComponentResponse',
  full_name='ComponentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ComponentResponse.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='ComponentResponse.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ComponentResponse.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['PlatformRequest'] = _PLATFORMREQUEST
DESCRIPTOR.message_types_by_name['ComponentResponse'] = _COMPONENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlatformRequest = _reflection.GeneratedProtocolMessageType('PlatformRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLATFORMREQUEST,
  '__module__' : 'cloudx_connector_pb2'
  # @@protoc_insertion_point(class_scope:PlatformRequest)
  })
_sym_db.RegisterMessage(PlatformRequest)

ComponentResponse = _reflection.GeneratedProtocolMessageType('ComponentResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPONENTRESPONSE,
  '__module__' : 'cloudx_connector_pb2'
  # @@protoc_insertion_point(class_scope:ComponentResponse)
  })
_sym_db.RegisterMessage(ComponentResponse)



_CLOUDXCONNECTOR = _descriptor.ServiceDescriptor(
  name='CloudxConnector',
  full_name='CloudxConnector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=123,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShowComponents',
    full_name='CloudxConnector.ShowComponents',
    index=0,
    containing_service=None,
    input_type=_PLATFORMREQUEST,
    output_type=_COMPONENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLOUDXCONNECTOR)

DESCRIPTOR.services_by_name['CloudxConnector'] = _CLOUDXCONNECTOR

# @@protoc_insertion_point(module_scope)
